remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

logo: /photo.jpg

links: 
  - name: Email
    url: test
  - name: GitHub
    url: test
  - name: LinkedIn
    url: test

show_downloads: false
google_analytics: Your Google Analytics tracking ID
