remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: [JÃ¡n Mikulec]
description: [I am currently a PhD candidate at Faculty of Informatics and Information Technologies at Slovak University of Technology in Bratislava. My research focuses on hardware secuirty of neural networks and side-channel analysis.]

show_downloads: [false]
google_analytics: [Your Google Analytics tracking ID]
