remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: [JÃ¡n Mikulec]
description: [I am currently a PhD candidate at [Faculty of Informatics and Information Technologies](https://www.fiit.stuba.sk/), [Slovak University of Technology](https://www.stuba.sk/english.html?page_id=132), Bratislava, Slovakia.]

show_downloads: [false]
google_analytics: [Your Google Analytics tracking ID]
