remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

logo: /photo.jpg

description: PhD Candidate at Faculty ad [Informatics and Information Technologies](https://www.fiit.stuba.sk/), [Slovak University of Technology](https://www.stuba.sk/) in Bratislava, Slovakia.

show_downloads: false
google_analytics: Your Google Analytics tracking ID
