remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

logo: /photo.jpg

description: PhD Candidate at Faculty of Informatics and Information Technologies, Slovak University of Technology in Bratislava, Slovakia.

show_downloads: false
google_analytics: Your Google Analytics tracking ID
